name: Update M3U8 Links

on:
  schedule:
    - cron: "0 */6 * * *"  # Hər 6 saatda bir işlə
  workflow_dispatch:  # Manual trigger üçün

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python update_links.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update M3U8 links"
          git push
