name: run main.py

on:
  schedule:
    - cron: '0 */2 * * *'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Kodu klonla
        uses: actions/checkout@v4

      - name: Python quraşdır
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Asılılıqları yüklə
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Skripti işə sal
        run: python main.py config.json

      - name: Git status-u göstər
        run: git status

      - name: Faylları commit və push et
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add streams/*.m3u8 || true
          git commit -m "updated streams" || echo "No changes to commit"
          git push
